name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - decentralised-firestore

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Firebase Hosting
        uses: firebase/actions-deploy@v1
        with:
          token: ${{ -----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDVcSa/AypTb6w0\nr40ZrFkJfZMmUuTTRRh0P3ZAZYcTih/YwLkQqw7REABMWOwkkOHMCx3zlp5llLsy\nk3e40XZJf0JgBLWZLuCHRW2tOSMsYyieFxnyVftBanHH1vICIMcYLdst2ge8HlvT\nIerRr77fpUNB+3sugELlCFbev9oa63ZUtD31dJob4fkXfzu1Lr/6fCvH7M50Unpo\nAr/Q8gKKq1EOj6uNfgOya5wEtdhia26K/62jbQUz/+P/bTa2+HYVQD6EW1F9vLUO\nYI8Yb1MbsrD/f8/FhSRTR9/yWH3OqeFSGY6txobt3b4LL66YO2chny8tl8nrTe81\npk48HZGzAgMBAAECggEATLAyBrFhdMcL7YYhwVauSv2mcD+aXdpWlfXzS+HurXOU\nS7G7DKUZVr5UDRpqBh1UM5bO9SVp1f+hXuOjQXFo+bFSrOMkSFySaaflZza/T4R1\nJJAST4LbGr7fELlHDMKwJhzbwlazLsENpwdpsltdzkc3qi5sLOICpv3fEHuIJuFI\n3xd5iCjmA1/Ro2xl206r0jsC8F+8MSmzYqQSG4h4V75NTSuoG27RhgJKQj1AUn19\nf7UdD1C34PZW5zjmj5Ui9gUgCtPSTU/IwVXAZ514XKOewZONPWeAk6YlbJmNVIA5\nOzT79S2uUc32BoZinEuGA+S6QuenlcAESoF35gM9IQKBgQD1bUpFvWyfavUg+Vb9\njMU1fZVrOkw4hL51FvVN2oBxtkuhR9L7ya7BjN1gwx5dUydzSOKgn1l5KlXSsBqC\nJ/4Lu0mg0TI2ioQUYnf9Wk73C01LTA/KOKOSRzUz8oLTTeBLOgh0plXn2NdR8W/i\n+Btp3uX42/4pvAPbPhz/z5/EowKBgQDeoxzyTDRmXPlxz5Ms7dyK0KvFOVSQOq6p\nabdBdOjrI9GDwD87pv00Ecrkw8QXv3UJFcsGbEOQ49xGf/SAvOd+EkBkUZCzss3u\nKjknitABgAofo/PjfT1Dmt38aRXjDtgdMbCA17SZCv+IBm+wolSbFUVe5YYSoOef\nMoTVZ1u/sQKBgQDDjJMTQjzcQKKT5VeUqqcvWaLGTysQFWSTcvl9UM3qzK8yEEJh\ncG8XtJ9nS9BT17+lMbuw84ac7kh3mO1mK2tV+aJOyqBRqMhYXaTxbxVf7ddmWXJz\nU/GwyZ/whhgLOQ+voMu/9hCYrMPTfKYDmGBvWLSwNskqg64m8DS29r18NQKBgHKk\nhZxTF0x6pcwwOjYRidZFW54kRmI6hYQhNsdS/zlN6W4xiZ4bABlW7CZelFQyN37l\nJPV6vFQYsW3wJ6Q/IekuVtARnDScZyQzw9iTx0Zue0gNseG7tNdiINr/9dBE7Y4i\n7yN5b7q7ChguUEchX/W3v0/9Wsuu5XZ5miMVpQ4RAoGAEffeLZCqa0Zk8l5X3CRH\nSqnEXJwnxlPCyvtCFenGLBXI4C9BfPq6+R4tB0rVN4ZKLFVgGFA10IrUGKo7cxpe\n6sDJhW3tMXVT9CeIQPPrOypNaY22/vbU2RKOer7XMuQma65ApXK+UfMnNIz3xGnF\nfe3fjI8m6vQBAIf3UNWk4iI=\n-----END PRIVATE KEY-----\n }}
          project_id: ${{ decentralised-ui }}
